# Generated by Django 5.2.12 on 2026-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='gateway_binding',
            field=models.CharField(blank=True, help_text='Optional OpenClaw node/session id', max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='kind',
            field=models.CharField(choices=[('voice', 'Voice'), ('automation', 'Automation'), ('other', 'Other')], default='voice', max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='mode',
            field=models.CharField(blank=True, help_text="Optional profile/mode, e.g. 'car'", max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='wake_word',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
