# Generated by Django 6.0.3 on 2026-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_agent_active_agent_gateway_binding_agent_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBuildBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IncomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_target_cents', models.BigIntegerField(default=8500000)),
                ('monthly_target_cents', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'verbose_name': 'Income profile',
                'verbose_name_plural': 'Income profiles',
            },
        ),
        migrations.CreateModel(
            name='IoTLabEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('last_touched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IoT lab entry',
                'verbose_name_plural': 'IoT lab entries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('proposal', 'Proposal'), ('active', 'Active'), ('paid', 'Paid')], default='lead', max_length=32)),
                ('expected_value_cents', models.BigIntegerField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
